---
- name: Restart postgresql
  environment:
    XDG_RUNTIME_DIR: "{{ foreman_xdg_runtime_dir }}"
  become: true
  become_user: "{{ foreman_service_user }}"
  ansible.builtin.systemd:
    name: "{{ postgresql_container_name }}"
    state: restarted
    scope: user
