---
- name: Deploy IOP Network
  ansible.builtin.include_role:
    name: podman_network
  vars:
    podman_network_name: "iop-core-network"
    podman_network_subnet: "10.130.0.0/24"
    podman_network_gateway: "10.130.0.1"
    podman_network_driver: "bridge"
    podman_network_internal: true

- name: Deploy IOP Kafka service
  ansible.builtin.include_role:
    name: iop_kafka

- name: Deploy IOP Ingress service
  ansible.builtin.include_role:
    name: iop_ingress

- name: Deploy IOP Puptoo service
  ansible.builtin.include_role:
    name: iop_puptoo
