---
- name: Restart engine
  environment:
    XDG_RUNTIME_DIR: "{{ foremanctl_xdg_runtime_dir }}"
  become: true
  become_user: "{{ foremanctl_user }}"
  ansible.builtin.systemd:
    name: iop-core-engine
    state: restarted
    scope: user
  listen: restart engine
  when: ansible_facts.services['iop-core-engine.service'] is defined
